package co.edu.unicauca.distribuidos.cliente_administrador.vista;

import java.util.List;

import javax.swing.JOptionPane;

import co.edu.unicauca.distribuidos.cliente_administrador.model.ProductoEntity;
import co.edu.unicauca.distribuidos.cliente_administrador.model.State;
import co.edu.unicauca.distribuidos.cliente_administrador.servicio.adminClientServices;
import co.edu.unicauca.distribuidos.cliente_administrador.servicio.adminClienteServicesProducts;


public class FrmSubastaAC extends javax.swing.JFrame{
     /**
     * Creates new form FrmSubastaAC
     */
    //private adminClienteServicesProducts objProductoS;
    adminClienteServicesProducts objProductService = new adminClienteServicesProducts();
    private List<ProductoEntity> listaProductos;
    public FrmSubastaAC() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAbrirSubasta = new javax.swing.JButton();
        btnCerrarSubasta = new javax.swing.JButton();
        txtIDProducto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        jLabel1.setText("Abrir / Cerrar Subasta");

        jLabel2.setText("Id articulo:");

        btnAbrirSubasta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAbrirSubasta.setText("Abrir Subasta");
        btnAbrirSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirSubastaActionPerformed(evt);
            }
        });

        btnCerrarSubasta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarSubasta.setText("Cerrar Subasta");
        btnCerrarSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSubastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAbrirSubasta)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrarSubasta)
                            .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSubasta)
                    .addComponent(btnAbrirSubasta))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
                   
    private void btnAbrirSubastaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        abrirSubasta();
        this.dispose();
        FrmInicio panel= new FrmInicio();
        panel.setVisible(true);
        
       
    }                                               

    private void btnCerrarSubastaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        cerrarSubasta();
        this.dispose();
        FrmInicio panel= new FrmInicio();
        panel.setVisible(true);
        
    }  
    private void abrirSubasta(){
        try{
        //adminClienteServicesProducts objProductService = new adminClienteServicesProducts();
        int idProducto = Integer.parseInt(this.txtIDProducto.getText());
            if(null != objProductService.AbrirSubastaProducto(idProducto) ){
            JOptionPane.showMessageDialog(this, "Subasta Abierta");
            }else {
                JOptionPane.showMessageDialog(this, "No fue posible abrir la subasta,verifique que el id del producto existe");
            }
            }catch(java.lang.NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Formato de entrada invalido");
            }
        //}
    }
    private void cerrarSubasta(){
        try{
        int idProducto = Integer.parseInt(this.txtIDProducto.getText());
        
        if(null!=objProductService.CerrarSubastaProducto(idProducto) ){
        JOptionPane.showMessageDialog(this, "Subasta cerrada");
        }else {
            JOptionPane.showMessageDialog(this, "No fue posible cerrar la subasta,verifique que el id del producto existe");
        }
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Formato de entrada invalido");
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSubastaAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSubastaAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSubastaAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSubastaAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSubastaAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAbrirSubasta;
    private javax.swing.JButton btnCerrarSubasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtIDProducto;
    // End of variables declaration  
}
